const fs = require('fs/promises');
const path = require('path');
const { app } = require('electron');

// Default profile shipped with the app so a brand-new install has something
// sensible to show in the setup UI and overlay immediately, instead of a
// blank slate. Users edit this through the React setup UI, not by hand.
//
// styleBars/activeStyleBarId support multiple ability bars (melee/ranged/
// magic, say) that can be switched between - manually, by a cycle keybind,
// or automatically when a weapon-swap keybind is pressed (see
// electron/inputListener.js). Defaulting styleBars to [] means an existing
// profile from before this existed, or someone who just doesn't use
// multiple styles, keeps behaving exactly like a single flat keybind list -
// every keybind has no styleBarId (or an old profile has none at all),
// which is treated as "shared", i.e. always active.
const DEFAULT_PROFILE = {
  settings: {
    iconCount: 8,
    alwaysOnTop: true,
    theme: 'dark',
    cycleBarKey: null
  },
  keybinds: [],
  styleBars: [],
  activeStyleBarId: null
};

// --- Multiple saved profiles -------------------------------------------
//
// A player can keep several named profiles (e.g. "Solo bossing",
// "Group PvM") and switch between them from inside the app, rather than
// only having one active setup plus file-based export/import. Layout on
// disk, under app.getPath('userData'):
//
//   profiles/
//     manifest.json        { activeProfileId, profiles: [{ id, name }] }
//     <id>.json             one Profile object per saved profile
//
// The manifest is the source of truth for *which* profiles exist and their
// display names; the id files hold the actual keybind data. Kept separate
// so renaming or listing profiles never requires reading every profile's
// full contents.
function getProfilesDir() {
  return path.join(app.getPath('userData'), 'profiles');
}

function getManifestPath() {
  return path.join(getProfilesDir(), 'manifest.json');
}

function getProfileFilePath(id) {
  return path.join(getProfilesDir(), `${id}.json`);
}

function makeProfileId() {
  return `p-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

// Optional, bundled with the app (not generated by it) - a maintainer can
// build this out in the setup UI like any other profile (add abilities to
// each style bar, but never press a key for them, so every keybind's `key`
// stays ''), Export it, and drop the exported file here. Used below to seed
// the very first profile on a genuinely fresh install, so first-time setup
// is "press key for each already-listed ability" rather than "search and
// add every single one from scratch". Without this file existing, nothing
// changes: falls straight back to DEFAULT_PROFILE.
const STARTER_PROFILE_PATH = path.join(__dirname, '..', 'data', 'starter-profile.json');

// A shallow {...DEFAULT_PROFILE, ...loaded} would let an old saved
// profile's `settings` object (saved before cycleBarKey existed) silently
// wipe out that default by replacing the whole object - merge settings one
// level deep so new setting fields always have a value. Used for every
// profile read from disk, whichever saved profile it is, plus importing a
// profile someone exported from another machine, possibly on an older
// version of the app.
function normalizeProfile(loaded) {
  return {
    ...DEFAULT_PROFILE,
    ...loaded,
    settings: { ...DEFAULT_PROFILE.settings, ...(loaded.settings || {}) }
  };
}

async function loadStarterProfile() {
  try {
    const raw = await fs.readFile(STARTER_PROFILE_PATH, 'utf-8');
    return normalizeProfile(JSON.parse(raw));
  } catch (err) {
    if (err.code !== 'ENOENT') {
      console.warn('Could not read bundled starter profile, using empty default:', err.message);
    }
    return DEFAULT_PROFILE;
  }
}

async function ensureProfilesDir() {
  await fs.mkdir(getProfilesDir(), { recursive: true });
}

async function readManifest() {
  try {
    return JSON.parse(await fs.readFile(getManifestPath(), 'utf-8'));
  } catch (err) {
    if (err.code !== 'ENOENT') throw err;
    return null;
  }
}

async function writeManifest(manifest) {
  await ensureProfilesDir();
  await fs.writeFile(getManifestPath(), JSON.stringify(manifest, null, 2), 'utf-8');
}

async function writeProfileFile(id, profileData) {
  await ensureProfilesDir();
  await fs.writeFile(getProfileFilePath(id), JSON.stringify(profileData, null, 2), 'utf-8');
}

async function readProfileFile(id) {
  const raw = await fs.readFile(getProfileFilePath(id), 'utf-8');
  return normalizeProfile(JSON.parse(raw));
}

// Ensures the manifest exists, creating it on first-ever run of this
// multi-profile system. Two cases:
//  - An older, pre-multi-profile install has userData/profile.json (the
//    single-file layout this replaced) - migrate its content in as the
//    first saved profile ("Default") rather than discarding it.
//  - Nothing at all exists yet (a genuinely fresh install) - seed the first
//    profile from the bundled starter profile, or an empty default if
//    there isn't one.
async function ensureManifest() {
  const existing = await readManifest();
  if (existing) return existing;

  const legacyPath = path.join(app.getPath('userData'), 'profile.json');
  let seedProfile = null;
  let seedName = 'Default';
  try {
    seedProfile = normalizeProfile(JSON.parse(await fs.readFile(legacyPath, 'utf-8')));
  } catch (err) {
    if (err.code !== 'ENOENT') {
      console.warn('Could not read legacy profile.json during migration:', err.message);
    }
  }
  if (!seedProfile) {
    seedProfile = await loadStarterProfile();
    if (seedProfile !== DEFAULT_PROFILE) seedName = 'Starter';
  }

  const id = makeProfileId();
  await writeProfileFile(id, seedProfile);
  const manifest = { activeProfileId: id, profiles: [{ id, name: seedName }] };
  await writeManifest(manifest);
  return manifest;
}

async function listProfiles() {
  const manifest = await ensureManifest();
  return { activeProfileId: manifest.activeProfileId, profiles: manifest.profiles };
}

async function loadActiveProfile() {
  const manifest = await ensureManifest();
  return { id: manifest.activeProfileId, profile: await readProfileFile(manifest.activeProfileId) };
}

// Saves content into a specific profile slot (used for both the regular
// auto-save/Save-button path and import, both of which write into whichever
// profile is currently active) - does not touch the manifest, since this
// never adds, removes, renames, or switches profiles.
async function saveActiveProfile(id, profileData) {
  await writeProfileFile(id, profileData);
}

async function switchActiveProfile(id) {
  const manifest = await ensureManifest();
  if (!manifest.profiles.some((p) => p.id === id)) {
    throw new Error(`No saved profile with id ${id}`);
  }
  manifest.activeProfileId = id;
  await writeManifest(manifest);
  return readProfileFile(id);
}

async function createProfile(name) {
  const manifest = await ensureManifest();
  const id = makeProfileId();
  await writeProfileFile(id, DEFAULT_PROFILE);
  manifest.profiles.push({ id, name });
  manifest.activeProfileId = id;
  await writeManifest(manifest);
  return { id, profile: DEFAULT_PROFILE };
}

async function duplicateProfile(sourceId, name) {
  const manifest = await ensureManifest();
  const source = await readProfileFile(sourceId);
  const id = makeProfileId();
  await writeProfileFile(id, source);
  manifest.profiles.push({ id, name });
  manifest.activeProfileId = id;
  await writeManifest(manifest);
  return { id, profile: source };
}

async function renameProfile(id, name) {
  const manifest = await ensureManifest();
  const entry = manifest.profiles.find((p) => p.id === id);
  if (!entry) throw new Error(`No saved profile with id ${id}`);
  entry.name = name;
  await writeManifest(manifest);
}

// Returns the newly-active { id, profile } if deleting this one meant
// switching to another (because it was the active one), or null if the
// deleted profile wasn't active - nothing else needs to change in that
// case. Refuses to delete the last remaining profile - there always has to
// be at least one, same as the app always having *some* active keybind
// list to track.
async function deleteProfile(id) {
  const manifest = await ensureManifest();
  const idx = manifest.profiles.findIndex((p) => p.id === id);
  if (idx === -1) throw new Error(`No saved profile with id ${id}`);
  if (manifest.profiles.length === 1) {
    throw new Error('Cannot delete the only remaining profile');
  }
  manifest.profiles.splice(idx, 1);
  await fs.rm(getProfileFilePath(id), { force: true });

  let switched = null;
  if (manifest.activeProfileId === id) {
    manifest.activeProfileId = manifest.profiles[0].id;
    switched = { id: manifest.activeProfileId, profile: await readProfileFile(manifest.activeProfileId) };
  }
  await writeManifest(manifest);
  return switched;
}

module.exports = {
  DEFAULT_PROFILE,
  normalizeProfile,
  listProfiles,
  loadActiveProfile,
  saveActiveProfile,
  switchActiveProfile,
  createProfile,
  duplicateProfile,
  renameProfile,
  deleteProfile
};
